### ISSUE TITLE
[Question] How to deal with cold start

### ISSUE THREAD

**Issue by risufaj** [fidelity/mabwiser#64]
Hi mabwiser team,

Thank you for this great library! 

I am wondering what would be the best approach for mabwiser to be used in cold start situations, where there aren't yet any recorded decisions and rewards. Could it be possible to initialize rewards for all arms with 0? The use case I have in mind has binary rewards [0,1].

Thanks in advance!

**Comment by bkleyn** [comment]
Hi @risufaj!

Thank for your interest in the library.

Great question! Cold-start is a challenging problem in many recommender system problems. Note we have a `warm_start` function in the [MAB](https://github.com/fidelity/mabwiser/blob/master/mabwiser/mab.py#L670) object that can be used to warm-start cold arms. In order to warm-start the multi-armed bandit we need a list of features for each arm that can be used to calculate pairwise similarities between the arms. See [here](https://github.com/fidelity/mabwiser/blob/master/examples/contextual_mab.py#L74) for an example how it's used.

**Comment by risufaj** [comment]
Hi @bkleyn,

Thank you for answering! 

I understand that using the function you mentioned, it would be possible to warm start an arm that is most similar to some existing arms, for which you have data. In situations where there aren't any data recorded for any of the arms, I suppose the best could be to have some sort of data collection phase, right?

**Comment by bkleyn** [comment]
Yes, indeed! This is in fact an active research area, and we recently studied how to speed-up that data collection phase with publications at [CPAIOR'21](https://link.springer.com/chapter/10.1007/978-3-030-78230-6_27) and [IJCAI'21](https://arxiv.org/abs/2112.03105).
